import prisma from "../../src/prisma/client";

export const seedModels = async () => {
  const apple = await prisma.mobileBrand.findUnique({ where: { name: "Apple" } });
  const samsung = await prisma.mobileBrand.findUnique({ where: { name: "Samsung" } });
  const xiaomi = await prisma.mobileBrand.findUnique({ where: { name: "Xiaomi" } });
  const oppo = await prisma.mobileBrand.findUnique({ where: { name: "Oppo" } });
  const vivo = await prisma.mobileBrand.findUnique({ where: { name: "Vivo" } });

  if (!apple || !samsung || !xiaomi || !oppo || !vivo) {
    throw new Error("Brands not found. Seed brands first.");
  }

  const models = [
    // Apple (4)
    {
      brandId: apple.id,
      modelName: "iPhone 15 Pro",
      photo: "/models/iphone15pro.png",
      storage: "256GB",
      ram: "8GB",
      color: "Black",
      purchasePrice: 900,
      sellingPrice: 1200,
      stockQty: 10,
      status: "ACTIVE",
    },
    {
      brandId: apple.id,
      modelName: "iPhone 14",
      photo: "/models/iphone14.png",
      storage: "128GB",
      ram: "6GB",
      color: "Blue",
      purchasePrice: 700,
      sellingPrice: 950,
      stockQty: 12,
      status: "ACTIVE",
    },
    {
      brandId: apple.id,
      modelName: "iPhone 13",
      photo: "/models/iphone13.png",
      storage: "128GB",
      ram: "6GB",
      color: "White",
      purchasePrice: 600,
      sellingPrice: 800,
      stockQty: 15,
      status: "ACTIVE",
    },
    {
      brandId: apple.id,
      modelName: "iPhone SE",
      photo: "/models/iphonese.png",
      storage: "64GB",
      ram: "4GB",
      color: "Red",
      purchasePrice: 300,
      sellingPrice: 450,
      stockQty: 20,
      status: "ACTIVE",
    },

    // Samsung (4)
    {
      brandId: samsung.id,
      modelName: "Galaxy S24",
      photo: "/models/s24.png",
      storage: "256GB",
      ram: "12GB",
      color: "Silver",
      purchasePrice: 750,
      sellingPrice: 1000,
      stockQty: 10,
      status: "ACTIVE",
    },
    {
      brandId: samsung.id,
      modelName: "Galaxy S23",
      photo: "/models/s23.png",
      storage: "256GB",
      ram: "8GB",
      color: "Black",
      purchasePrice: 650,
      sellingPrice: 850,
      stockQty: 11,
      status: "ACTIVE",
    },
    {
      brandId: samsung.id,
      modelName: "Galaxy A54",
      photo: "/models/a54.png",
      storage: "128GB",
      ram: "8GB",
      color: "Purple",
      purchasePrice: 350,
      sellingPrice: 500,
      stockQty: 18,
      status: "ACTIVE",
    },
    {
      brandId: samsung.id,
      modelName: "Galaxy A34",
      photo: "/models/a34.png",
      storage: "128GB",
      ram: "6GB",
      color: "Green",
      purchasePrice: 280,
      sellingPrice: 400,
      stockQty: 20,
      status: "ACTIVE",
    },

    // Xiaomi (4)
    {
      brandId: xiaomi.id,
      modelName: "Redmi Note 13",
      photo: "/models/note13.png",
      storage: "256GB",
      ram: "8GB",
      color: "Blue",
      purchasePrice: 200,
      sellingPrice: 300,
      stockQty: 25,
      status: "ACTIVE",
    },
    {
      brandId: xiaomi.id,
      modelName: "Poco X5",
      photo: "/models/pocox5.png",
      storage: "128GB",
      ram: "6GB",
      color: "Black",
      purchasePrice: 180,
      sellingPrice: 280,
      stockQty: 22,
      status: "ACTIVE",
    },
    {
      brandId: xiaomi.id,
      modelName: "Mi 11 Lite",
      photo: "/models/mi11lite.png",
      storage: "128GB",
      ram: "6GB",
      color: "Pink",
      purchasePrice: 220,
      sellingPrice: 320,
      stockQty: 15,
      status: "ACTIVE",
    },
    {
      brandId: xiaomi.id,
      modelName: "Redmi 12",
      photo: "/models/redmi12.png",
      storage: "128GB",
      ram: "4GB",
      color: "Gray",
      purchasePrice: 150,
      sellingPrice: 220,
      stockQty: 30,
      status: "ACTIVE",
    },

    // Oppo (4)
    {
      brandId: oppo.id,
      modelName: "Oppo Reno 11",
      photo: "/models/reno11.png",
      storage: "256GB",
      ram: "8GB",
      color: "Gold",
      purchasePrice: 300,
      sellingPrice: 450,
      stockQty: 16,
      status: "ACTIVE",
    },
    {
      brandId: oppo.id,
      modelName: "Oppo A78",
      photo: "/models/a78.png",
      storage: "128GB",
      ram: "8GB",
      color: "Black",
      purchasePrice: 220,
      sellingPrice: 330,
      stockQty: 18,
      status: "ACTIVE",
    },
    {
      brandId: oppo.id,
      modelName: "Oppo Find X5",
      photo: "/models/findx5.png",
      storage: "256GB",
      ram: "12GB",
      color: "White",
      purchasePrice: 600,
      sellingPrice: 800,
      stockQty: 8,
      status: "ACTIVE",
    },
    {
      brandId: oppo.id,
      modelName: "Oppo A58",
      photo: "/models/a58.png",
      storage: "128GB",
      ram: "6GB",
      color: "Green",
      purchasePrice: 180,
      sellingPrice: 250,
      stockQty: 20,
      status: "ACTIVE",
    },

    // Vivo (4)
    {
      brandId: vivo.id,
      modelName: "Vivo V29",
      photo: "/models/v29.png",
      storage: "256GB",
      ram: "12GB",
      color: "Blue",
      purchasePrice: 350,
      sellingPrice: 500,
      stockQty: 14,
      status: "ACTIVE",
    },
    {
      brandId: vivo.id,
      modelName: "Vivo Y100",
      photo: "/models/y100.png",
      storage: "128GB",
      ram: "8GB",
      color: "Pink",
      purchasePrice: 250,
      sellingPrice: 350,
      stockQty: 18,
      status: "ACTIVE",
    },
    {
      brandId: vivo.id,
      modelName: "Vivo Y36",
      photo: "/models/y36.png",
      storage: "128GB",
      ram: "6GB",
      color: "Gold",
      purchasePrice: 200,
      sellingPrice: 280,
      stockQty: 22,
      status: "ACTIVE",
    },
    {
      brandId: vivo.id,
      modelName: "Vivo X90",
      photo: "/models/x90.png",
      storage: "256GB",
      ram: "12GB",
      color: "Black",
      purchasePrice: 600,
      sellingPrice: 850,
      stockQty: 10,
      status: "ACTIVE",
    },
  ];

  await prisma.mobileModel.createMany({
    data: models,
  });

  console.log("✅ 20 Mobile Models seeded");

}