import prisma from "../../src/prisma/client";

const productsData = [
  {
    brand: "Apple",
    category: "Smart Phone",
    modelName: "iPhone 15 Pro Max",
    photo: "/products/iphone-15-pro-max.png",
    storage: "256GB",
    ram: "8GB",
    spec: "A17 Pro Chip, Super Retina XDR OLED, 48MP Camera",
    color: "Natural Titanium",
    purchasePrice: 950,
    sellingPrice: 1200,
    stockQty: 10,
    status: "ACTIVE",
  },
  {
    brand: "Apple",
    category: "Smart Phone",
    modelName: "iPhone 16 Pro",
    photo: "/products/iphone-16-pro.png",
    storage: "256GB",
    ram: "8GB",
    spec: "A18 Pro Chip, OLED Display, Pro Camera System",
    color: "Black Titanium",
    purchasePrice: 1050,
    sellingPrice: 1350,
    stockQty: 8,
    status: "ACTIVE",
  },
  {
    brand: "Samsung",
    category: "Smart Phone",
    modelName: "Galaxy S25 Ultra",
    photo: "/products/s25-ultra.png",
    storage: "512GB",
    ram: "12GB",
    spec: "Snapdragon Elite, AMOLED Display, 200MP Camera",
    color: "Titanium Gray",
    purchasePrice: 900,
    sellingPrice: 1150,
    stockQty: 12,
    status: "ACTIVE",
  },
  {
    brand: "Samsung",
    category: "Smart Phone",
    modelName: "Galaxy A56 5G",
    photo: "/products/a56.png",
    storage: "256GB",
    ram: "8GB",
    spec: "Exynos Processor, Super AMOLED Display",
    color: "Awesome Blue",
    purchasePrice: 280,
    sellingPrice: 380,
    stockQty: 20,
    status: "ACTIVE",
  },
  {
    brand: "Xiaomi",
    category: "Smart Phone",
    modelName: "Redmi Note 14 Pro",
    photo: "/products/redmi-note-14-pro.png",
    storage: "256GB",
    ram: "12GB",
    spec: "AMOLED Display, 200MP Camera, Fast Charging",
    color: "Midnight Black",
    purchasePrice: 220,
    sellingPrice: 320,
    stockQty: 25,
    status: "ACTIVE",
  },
  {
    brand: "Oppo",
    category: "Smart Phone",
    modelName: "Oppo Reno 13",
    photo: "/products/oppo-reno-13.png",
    storage: "256GB",
    ram: "12GB",
    spec: "AI Camera, AMOLED Display",
    color: "White",
    purchasePrice: 350,
    sellingPrice: 480,
    stockQty: 15,
    status: "ACTIVE",
  },

  // Accessories
  {
    brand: "Anker",
    category: "Power & Charging",
    modelName: "Anker 65W GaN Charger",
    photo: "/products/anker-65w.png",
    spec: "USB-C Fast Charger",
    color: "Black",
    purchasePrice: 25,
    sellingPrice: 45,
    stockQty: 50,
    status: "ACTIVE",
  },
  {
    brand: "Baseus",
    category: "Cables & Adapters",
    modelName: "Baseus USB-C Cable 100W",
    photo: "/products/baseus-cable.png",
    spec: "Fast Charging Data Cable",
    color: "Black",
    purchasePrice: 8,
    sellingPrice: 15,
    stockQty: 100,
    status: "ACTIVE",
  },
  {
    brand: "JBL",
    category: "Earphone",
    modelName: "JBL Tune Buds",
    photo: "/products/jbl-tune-buds.png",
    spec: "Wireless Bluetooth Earbuds",
    color: "Black",
    purchasePrice: 40,
    sellingPrice: 70,
    stockQty: 30,
    status: "ACTIVE",
  },
  {
    brand: "Vivo",
    category: "Smart Phone",
    modelName: "Vivo V40 Pro",
    photo: "/products/vivo-v40-pro.png",
    storage: "512GB",
    ram: "12GB",
    spec: "AMOLED Display, Dimensity Processor, ZEISS Camera",
    color: "Titanium Gray",
    purchasePrice: 420,
    sellingPrice: 550,
    stockQty: 12,
    status: "ACTIVE",
  },
  {
    brand: "Realme",
    category: "Smart Phone",
    modelName: "Realme GT 6",
    photo: "/products/realme-gt-6.png",
    storage: "256GB",
    ram: "12GB",
    spec: "Snapdragon Processor, AMOLED 120Hz Display",
    color: "Silver",
    purchasePrice: 350,
    sellingPrice: 470,
    stockQty: 18,
    status: "ACTIVE",
  },
  {
    brand: "OnePlus",
    category: "Smart Phone",
    modelName: "OnePlus 13",
    photo: "/products/oneplus-13.png",
    storage: "256GB",
    ram: "12GB",
    spec: "Snapdragon Elite, AMOLED Display, Fast Charging",
    color: "Black",
    purchasePrice: 650,
    sellingPrice: 850,
    stockQty: 10,
    status: "ACTIVE",
  },
  {
    brand: "Huawei",
    category: "Smart Phone",
    modelName: "Huawei Pura 70 Pro",
    photo: "/products/huawei-pura-70.png",
    storage: "512GB",
    ram: "12GB",
    spec: "OLED Display, Advanced Camera System",
    color: "White",
    purchasePrice: 700,
    sellingPrice: 900,
    stockQty: 8,
    status: "ACTIVE",
  },
  {
    brand: "Tecno",
    category: "Smart Phone",
    modelName: "Tecno Camon 30 Pro",
    photo: "/products/tecno-camon-30.png",
    storage: "256GB",
    ram: "8GB",
    spec: "AMOLED Display, 50MP Camera",
    color: "Blue",
    purchasePrice: 220,
    sellingPrice: 330,
    stockQty: 25,
    status: "ACTIVE",
  },
  {
    brand: "Nokia",
    category: "Smart Phone",
    modelName: "Nokia G42 5G",
    photo: "/products/nokia-g42.png",
    storage: "128GB",
    ram: "6GB",
    spec: "5G Smartphone, Durable Design",
    color: "Purple",
    purchasePrice: 150,
    sellingPrice: 230,
    stockQty: 20,
    status: "ACTIVE",
  },
  {
    brand: "Dell",
    category: "Laptop",
    modelName: "Dell Inspiron 15",
    photo: "/products/dell-inspiron-15.png",
    storage: "512GB SSD",
    ram: "16GB",
    spec: "Intel Core i5, Full HD Display",
    color: "Silver",
    purchasePrice: 500,
    sellingPrice: 700,
    stockQty: 6,
    status: "ACTIVE",
  },
  {
    brand: "HP",
    category: "Laptop",
    modelName: "HP Pavilion 15",
    photo: "/products/hp-pavilion-15.png",
    storage: "512GB SSD",
    ram: "16GB",
    spec: "Intel Core i7, FHD Display",
    color: "Silver",
    purchasePrice: 650,
    sellingPrice: 850,
    stockQty: 5,
    status: "ACTIVE",
  },
  {
    brand: "Lenovo",
    category: "Laptop",
    modelName: "Lenovo ThinkPad E14",
    photo: "/products/thinkpad-e14.png",
    storage: "512GB SSD",
    ram: "16GB",
    spec: "Business Laptop, Intel Core i5",
    color: "Black",
    purchasePrice: 550,
    sellingPrice: 750,
    stockQty: 7,
    status: "ACTIVE",
  },
  {
    brand: "Asus",
    category: "Laptop",
    modelName: "ASUS ROG Strix G16",
    photo: "/products/rog-strix-g16.png",
    storage: "1TB SSD",
    ram: "32GB",
    spec: "Gaming Laptop, RTX Graphics",
    color: "Black",
    purchasePrice: 1200,
    sellingPrice: 1600,
    stockQty: 4,
    status: "ACTIVE",
  },
  {
    brand: "Sony",
    category: "Headphone",
    modelName: "Sony WH-1000XM5",
    photo: "/products/sony-xm5.png",
    storage: null,
    ram: null,
    spec: "Noise Cancelling Wireless Headphone",
    color: "Black",
    purchasePrice: 250,
    sellingPrice: 380,
    stockQty: 15,
    status: "ACTIVE",
  },
  {
    brand: "JBL",
    category: "Headphone",
    modelName: "JBL Live 660NC",
    photo: "/products/jbl-live-660.png",
    storage: null,
    ram: null,
    spec: "Bluetooth Noise Cancelling Headset",
    color: "Blue",
    purchasePrice: 90,
    sellingPrice: 150,
    stockQty: 20,
    status: "ACTIVE",
  },
  {
    brand: "Anker",
    category: "Power & Charging",
    modelName: "Anker PowerCore 20000",
    photo: "/products/anker-powercore.png",
    storage: null,
    ram: null,
    spec: "20000mAh Fast Charging Power Bank",
    color: "Black",
    purchasePrice: 25,
    sellingPrice: 45,
    stockQty: 50,
    status: "ACTIVE",
  },
  {
    brand: "Baseus",
    category: "Power & Charging",
    modelName: "Baseus 100W Power Bank",
    photo: "/products/baseus-powerbank.png",
    storage: null,
    ram: null,
    spec: "Fast Charging PD Power Bank",
    color: "Gray",
    purchasePrice: 35,
    sellingPrice: 60,
    stockQty: 35,
    status: "ACTIVE",
  },
  {
    brand: "Logitech",
    category: "Computer Accessories",
    modelName: "Logitech MX Master 3S",
    photo: "/products/mx-master-3s.png",
    storage: null,
    ram: null,
    spec: "Wireless Productivity Mouse",
    color: "Black",
    purchasePrice: 70,
    sellingPrice: 110,
    stockQty: 15,
    status: "ACTIVE",
  },
  {
    brand: "Apple",
    category: "Smart Wearables",
    modelName: "Apple Watch Series 10",
    photo: "/products/apple-watch-10.png",
    storage: "64GB",
    ram: null,
    spec: "Smart Watch, Health Tracking",
    color: "Black",
    purchasePrice: 300,
    sellingPrice: 450,
    stockQty: 10,
    status: "ACTIVE",
  },
  {
    brand: "Samsung",
    category: "Smart Wearables",
    modelName: "Galaxy Watch 7",
    photo: "/products/galaxy-watch-7.png",
    storage: "32GB",
    ram: "2GB",
    spec: "AMOLED Smart Watch, Fitness Tracking",
    color: "Green",
    purchasePrice: 180,
    sellingPrice: 280,
    stockQty: 12,
    status: "ACTIVE",
  },
  {
    brand: "Xiaomi",
    category: "Smart Wearables",
    modelName: "Xiaomi Smart Band 9",
    photo: "/products/mi-band-9.png",
    storage: null,
    ram: null,
    spec: "Fitness Tracker, AMOLED Display",
    color: "Black",
    purchasePrice: 25,
    sellingPrice: 45,
    stockQty: 40,
    status: "ACTIVE",
  },
  {
    brand: "Baseus",
    category: "Car Accessories",
    modelName: "Baseus Car Phone Holder",
    photo: "/products/baseus-holder.png",
    storage: null,
    ram: null,
    spec: "Dashboard Magnetic Phone Mount",
    color: "Black",
    purchasePrice: 10,
    sellingPrice: 25,
    stockQty: 60,
    status: "ACTIVE",
  },
  {
    brand: "Samsung",
    category: "Glass Protection",
    modelName: "Galaxy S25 Tempered Glass",
    photo: "/products/s25-glass.png",
    storage: null,
    ram: null,
    spec: "9H Tempered Glass Screen Protector",
    color: "Clear",
    purchasePrice: 3,
    sellingPrice: 10,
    stockQty: 100,
    status: "ACTIVE",
  },
];


export const seedProducts = async () => {
  for (const item of productsData) {

    const brand = await prisma.brand.findUnique({
      where: {
        name: item.brand,
      },
    });

    const category = await prisma.category.findUnique({
      where: {
        name: item.category,
      },
    });


    if (!brand || !category) {
      console.log(
        `❌ Missing brand/category: ${item.brand} - ${item.category}`
      );
      continue;
    }


    await prisma.product.create({
      data: {
        brandId: brand.id,
        categoryId: category.id,
        modelName: item.modelName,
        photo: item.photo ?? null,
        storage: item.storage ?? null,
        ram: item.ram ?? null,
        spec: item.spec,
        color: item.color,
        purchasePrice: item.purchasePrice,
        sellingPrice: item.sellingPrice,
        stockQty: item.stockQty,
        status: item.status,
      },
    });
  }

  console.log("✅ Products seeded");
};